
// system
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

// user
export const FEATCH_USER_REQUEST = 'FEATCH_USER_REQUEST'
export const FEATCH_USER_SUCCESS = 'FEATCH_USER_SUCCESS'
export const FEATCH_USER_FAILURE = 'FEATCH_USER_FAILURE'
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
